/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;




class DemoCodeTest {
   /*
    * This is for Demonstartion purpose only. 
    */
}

