/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment1;

import com.google.common.annotations.VisibleForTesting;

public class Ques2 {

/**
 * This file is for demonstration purpose only. 
 */

}
