/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab04;

import org.apache.commons.math3.geometry.spherical.oned.ArcsSet;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.util.*;
import java.util.stream.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.*;
import org.junit.jupiter.params.provider.*;

class SplittingTest {

    @ParameterizedTest
    @MethodSource("generator")
    void canBalance(String description, int[] nums, boolean expected) {
        boolean result = Splitting.canBalance(nums);
        assertEquals(expected, result);
    }

    private static Stream<Arguments> generator() {
        return Stream.of(
                Arguments.of("array is null", null, false),
                Arguments.of("empty array", new int[]{}, false),
                Arguments.of("single element array", new int[]{1}, false),
                Arguments.of("array can be split into two equal sums", new int[]{1, 2, 3, 4, 5, 5}, true),
                Arguments.of("array cannot be split into two equal sums", new int[]{1, 2, 3, 4}, false),
                Arguments.of("array with negative numbers can be split into two equal sums", new int[]{-1, 2, -3, 4}, true),
                Arguments.of("array with negative numbers cannot be split into two equal sums", new int[]{-1, 2, -3, 5}, false)
        );
    }
}
